In [531]:
import numpy as np
import pandas as pd
import os

In [532]:
os.getcwd()

'C:\\Users\\Admin\\3D Objects\\imarticus PGDA\\Machine learning\\Unsupervised Learning\\Principal Component Analysis (PCA)\\Dataset'

In [533]:
data =pd.read_csv('houseprice.csv')
df =data.copy(deep=True)
df

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,RL,62.0,7917,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,8,2007,WD,Normal,175000
1456,1457,20,RL,85.0,13175,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,MnPrv,NaN,0,2,2010,WD,Normal,210000
1457,1458,70,RL,66.0,9042,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,GdPrv,Shed,2500,5,2010,WD,Normal,266500
1458,1459,20,RL,68.0,9717,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,142125
1459,1460,20,RL,75.0,9937,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,6,2008,WD,Normal,147500

In [534]:
nulls=df.isnull().sum()
df_null=pd.DataFrame({'count':nulls,'percent':((nulls/df.shape[0])*100)})
df_null=df_null.sort_values('percent',ascending =False)
df_null

             count    percent
PoolQC        1453  99.520548
MiscFeature   1406  96.301370
Alley         1369  93.767123
Fence         1179  80.753425
FireplaceQu    690  47.260274
...            ...        ...
ExterQual        0   0.000000
Exterior2nd      0   0.000000
Exterior1st      0   0.000000
RoofMatl         0   0.000000
SalePrice        0   0.000000

[81 rows x 2 columns]

In [521]:
#df['Alley'].fillna('no',inplace=True)

In [535]:
df['BsmtQual'].unique()

array(['Gd', 'TA', 'Ex', nan, 'Fa'], dtype=object)

In [540]:
df['BsmtQual'].fillna('no',inplace=True)

In [541]:
df['BsmtExposure'].unique()
df['BsmtExposure'].fillna('nob',inplace=True)

In [542]:
df['BsmtFinType1'].fillna('nob',inplace=True)

In [543]:
df['BsmtFinType2'].fillna('nob',inplace=True)

In [544]:
df['FireplaceQu'].fillna('no',inplace=True)

In [545]:
df['GarageType'].fillna('nog',inplace=True)

In [546]:
df['GarageFinish'].fillna('nog',inplace=True)

In [548]:
df['GarageQual'].fillna('nog',inplace=True)

In [550]:
#DRopping high null values columns greater than 50% null
df.drop(['PoolQC','MiscFeature','Alley','Fence'],axis =1,inplace =True)

In [552]:
nulls=df.isnull().sum()
df_null=pd.DataFrame({'count':nulls,'percent':((nulls/df.shape[0])*100)})
df_null=df_null.sort_values('percent',ascending =False)
df_null[df_null.percent>0]

             count    percent
LotFrontage    259  17.739726
GarageYrBlt     81   5.547945
GarageCond      81   5.547945
BsmtCond        37   2.534247
MasVnrType       8   0.547945
MasVnrArea       8   0.547945
Electrical       1   0.068493

In [555]:
df.shape

(1460, 77)

In [556]:
df.LotFrontage.unique()

array([ 65.,  80.,  68.,  60.,  84.,  85.,  75.,  nan,  51.,  50.,  70.,
        91.,  72.,  66., 101.,  57.,  44., 110.,  98.,  47., 108., 112.,
        74., 115.,  61.,  48.,  33.,  52., 100.,  24.,  89.,  63.,  76.,
        81.,  95.,  69.,  21.,  32.,  78., 121., 122.,  40., 105.,  73.,
        77.,  64.,  94.,  34.,  90.,  55.,  88.,  82.,  71., 120., 107.,
        92., 134.,  62.,  86., 141.,  97.,  54.,  41.,  79., 174.,  99.,
        67.,  83.,  43., 103.,  93.,  30., 129., 140.,  35.,  37., 118.,
        87., 116., 150., 111.,  49.,  96.,  59.,  36.,  56., 102.,  58.,
        38., 109., 130.,  53., 137.,  45., 106., 104.,  42.,  39., 144.,
       114., 128., 149., 313., 168., 182., 138., 160., 152., 124., 153.,
        46.])

In [557]:
df.MasVnrArea.unique()

array([1.960e+02, 0.000e+00, 1.620e+02, 3.500e+02, 1.860e+02, 2.400e+02,
       2.860e+02, 3.060e+02, 2.120e+02, 1.800e+02, 3.800e+02, 2.810e+02,
       6.400e+02, 2.000e+02, 2.460e+02, 1.320e+02, 6.500e+02, 1.010e+02,
       4.120e+02, 2.720e+02, 4.560e+02, 1.031e+03, 1.780e+02, 5.730e+02,
       3.440e+02, 2.870e+02, 1.670e+02, 1.115e+03, 4.000e+01, 1.040e+02,
       5.760e+02, 4.430e+02, 4.680e+02, 6.600e+01, 2.200e+01, 2.840e+02,
       7.600e+01, 2.030e+02, 6.800e+01, 1.830e+02, 4.800e+01, 2.800e+01,
       3.360e+02, 6.000e+02, 7.680e+02, 4.800e+02, 2.200e+02, 1.840e+02,
       1.129e+03, 1.160e+02, 1.350e+02, 2.660e+02, 8.500e+01, 3.090e+02,
       1.360e+02, 2.880e+02, 7.000e+01, 3.200e+02, 5.000e+01, 1.200e+02,
       4.360e+02, 2.520e+02, 8.400e+01, 6.640e+02, 2.260e+02, 3.000e+02,
       6.530e+02, 1.120e+02, 4.910e+02, 2.680e+02, 7.480e+02, 9.800e+01,
       2.750e+02, 1.380e+02, 2.050e+02, 2.620e+02, 1.280e+02, 2.600e+02,
       1.530e+02, 6.400e+01, 3.120e+02, 1.600e+01, 9.220e+02, 1.420e+02,
       2.900e+02, 1.270e+02, 5.060e+02, 2.970e+02,       nan, 6.040e+02,
       2.540e+02, 3.600e+01, 1.020e+02, 4.720e+02, 4.810e+02, 1.080e+02,
       3.020e+02, 1.720e+02, 3.990e+02, 2.700e+02, 4.600e+01, 2.100e+02,
       1.740e+02, 3.480e+02, 3.150e+02, 2.990e+02, 3.400e+02, 1.660e+02,
       7.200e+01, 3.100e+01, 3.400e+01, 2.380e+02, 1.600e+03, 3.650e+02,
       5.600e+01, 1.500e+02, 2.780e+02, 2.560e+02, 2.250e+02, 3.700e+02,
       3.880e+02, 1.750e+02, 2.960e+02, 1.460e+02, 1.130e+02, 1.760e+02,
       6.160e+02, 3.000e+01, 1.060e+02, 8.700e+02, 3.620e+02, 5.300e+02,
       5.000e+02, 5.100e+02, 2.470e+02, 3.050e+02, 2.550e+02, 1.250e+02,
       1.000e+02, 4.320e+02, 1.260e+02, 4.730e+02, 7.400e+01, 1.450e+02,
       2.320e+02, 3.760e+02, 4.200e+01, 1.610e+02, 1.100e+02, 1.800e+01,
       2.240e+02, 2.480e+02, 8.000e+01, 3.040e+02, 2.150e+02, 7.720e+02,
       4.350e+02, 3.780e+02, 5.620e+02, 1.680e+02, 8.900e+01, 2.850e+02,
       3.600e+02, 9.400e+01, 3.330e+02, 9.210e+02, 7.620e+02, 5.940e+02,
       2.190e+02, 1.880e+02, 4.790e+02, 5.840e+02, 1.820e+02, 2.500e+02,
       2.920e+02, 2.450e+02, 2.070e+02, 8.200e+01, 9.700e+01, 3.350e+02,
       2.080e+02, 4.200e+02, 1.700e+02, 4.590e+02, 2.800e+02, 9.900e+01,
       1.920e+02, 2.040e+02, 2.330e+02, 1.560e+02, 4.520e+02, 5.130e+02,
       2.610e+02, 1.640e+02, 2.590e+02, 2.090e+02, 2.630e+02, 2.160e+02,
       3.510e+02, 6.600e+02, 3.810e+02, 5.400e+01, 5.280e+02, 2.580e+02,
       4.640e+02, 5.700e+01, 1.470e+02, 1.170e+03, 2.930e+02, 6.300e+02,
       4.660e+02, 1.090e+02, 4.100e+01, 1.600e+02, 2.890e+02, 6.510e+02,
       1.690e+02, 9.500e+01, 4.420e+02, 2.020e+02, 3.380e+02, 8.940e+02,
       3.280e+02, 6.730e+02, 6.030e+02, 1.000e+00, 3.750e+02, 9.000e+01,
       3.800e+01, 1.570e+02, 1.100e+01, 1.400e+02, 1.300e+02, 1.480e+02,
       8.600e+02, 4.240e+02, 1.047e+03, 2.430e+02, 8.160e+02, 3.870e+02,
       2.230e+02, 1.580e+02, 1.370e+02, 1.150e+02, 1.890e+02, 2.740e+02,
       1.170e+02, 6.000e+01, 1.220e+02, 9.200e+01, 4.150e+02, 7.600e+02,
       2.700e+01, 7.500e+01, 3.610e+02, 1.050e+02, 3.420e+02, 2.980e+02,
       5.410e+02, 2.360e+02, 1.440e+02, 4.230e+02, 4.400e+01, 1.510e+02,
       9.750e+02, 4.500e+02, 2.300e+02, 5.710e+02, 2.400e+01, 5.300e+01,
       2.060e+02, 1.400e+01, 3.240e+02, 2.950e+02, 3.960e+02, 6.700e+01,
       1.540e+02, 4.250e+02, 4.500e+01, 1.378e+03, 3.370e+02, 1.490e+02,
       1.430e+02, 5.100e+01, 1.710e+02, 2.340e+02, 6.300e+01, 7.660e+02,
       3.200e+01, 8.100e+01, 1.630e+02, 5.540e+02, 2.180e+02, 6.320e+02,
       1.140e+02, 5.670e+02, 3.590e+02, 4.510e+02, 6.210e+02, 7.880e+02,
       8.600e+01, 7.960e+02, 3.910e+02, 2.280e+02, 8.800e+01, 1.650e+02,
       4.280e+02, 4.100e+02, 5.640e+02, 3.680e+02, 3.180e+02, 5.790e+02,
       6.500e+01, 7.050e+02, 4.080e+02, 2.440e+02, 1.230e+02, 3.660e+02,
       7.310e+02, 4.480e+02, 2.940e+02, 3.100e+02, 2.370e+02, 4.260e+02,
       9.600e+01, 4.380e+02, 1.940e+02, 1.190e+02])

In [558]:
df.LotFrontage.fillna(df.LotFrontage.median(),inplace =True)
df.MasVnrArea.fillna(df.MasVnrArea.median(),inplace = True)
df.GarageYrBlt.fillna(df.GarageYrBlt.median(),inplace = True)

In [559]:
df.MasVnrArea.isnull().sum()

0

In [561]:
nulls=df.isnull().sum()
df_null=pd.DataFrame({'count':nulls,'percent':((nulls/df.shape[0])*100)})
df_null=df_null.sort_values('percent',ascending =False)
df_null[df_null.percent>0]

            count   percent
GarageCond     81  5.547945
BsmtCond       37  2.534247
MasVnrType      8  0.547945
Electrical      1  0.068493

In [566]:
df['GarageQual'].unique()

array(['TA', 'Fa', 'Gd', 'nog', 'Ex', 'Po'], dtype=object)

In [568]:
df['GarageCond'].unique()

KeyError: 'GarageCond'

In [562]:
df.drop('GarageCond',inplace =True,axis=1)

In [563]:
nulls=df.isnull().sum()
df_null=pd.DataFrame({'count':nulls,'percent':((nulls/df.shape[0])*100)})
df_null=df_null.sort_values('percent',ascending =False)
df_null[df_null.percent>0]

            count   percent
BsmtCond       37  2.534247
MasVnrType      8  0.547945
Electrical      1  0.068493

In [435]:
# df.drop(['BsmtExposure','BsmtFinType2','BsmtFinType1'],axis =1,inplace=True)

In [571]:
df.BsmtQual.unique()

array(['Gd', 'TA', 'Ex', 'no', 'Fa'], dtype=object)

In [570]:
df.BsmtCond.unique()

array(['TA', 'Gd', nan, 'Fa', 'Po'], dtype=object)

In [438]:
df.Electrical.value_counts()

SBrkr    1334
FuseA      94
FuseF      27
FuseP       3
Mix         1
Name: Electrical, dtype: int64

In [572]:
#Treating nulls
df.MasVnrType.fillna('none',inplace=True)
df.BsmtCond.fillna('TA',inplace=True)
df.Electrical.fillna('SBrkr',inplace=True)

In [573]:
nulls=df.isnull().sum()
df_null=pd.DataFrame({'count':nulls,'percent':((nulls/df.shape[0])*100)})
df_null=df_null.sort_values('percent',ascending =False)
df_null[df_null.percent>0]

Empty DataFrame
Columns: [count, percent]
Index: []

In [575]:
df_treated_new=df.copy(deep=True)

In [574]:
# df_treated=df.copy(deep=True)       (old treated data)
df_treated

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,LotShape,LandContour,Utilities,LotConfig,...,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,Reg,Lvl,AllPub,Inside,...,0,0,0,0,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,Reg,Lvl,AllPub,FR2,...,0,0,0,0,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,IR1,Lvl,AllPub,Inside,...,0,0,0,0,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,IR1,Lvl,AllPub,Corner,...,272,0,0,0,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,IR1,Lvl,AllPub,FR2,...,0,0,0,0,0,12,2008,WD,Normal,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,RL,62.0,7917,Pave,Reg,Lvl,AllPub,Inside,...,0,0,0,0,0,8,2007,WD,Normal,175000
1456,1457,20,RL,85.0,13175,Pave,Reg,Lvl,AllPub,Inside,...,0,0,0,0,0,2,2010,WD,Normal,210000
1457,1458,70,RL,66.0,9042,Pave,Reg,Lvl,AllPub,Inside,...,0,0,0,0,2500,5,2010,WD,Normal,266500
1458,1459,20,RL,68.0,9717,Pave,Reg,Lvl,AllPub,Inside,...,112,0,0,0,0,4,2010,WD,Normal,142125
1459,1460,20,RL,75.0,9937,Pave,Reg,Lvl,AllPub,Inside,...,0,0,0,0,0,6,2008,WD,Normal,147500

In [576]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 76 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             1460 non-null   int64
 1   MSSubClass     1460 non-null   int64
 2   MSZoning       1460 non-null   object
 3   LotFrontage    1460 non-null   float64
 4   LotArea        1460 non-null   int64
 5   Street         1460 non-null   object
 6   LotShape       1460 non-null   object
 7   LandContour    1460 non-null   object
 8   Utilities      1460 non-null   object
 9   LotConfig      1460 non-null   object
 10  LandSlope      1460 non-null   object
 11  Neighborhood   1460 non-null   object
 12  Condition1     1460 non-null   object
 13  Condition2     1460 non-null   object
 14  BldgType       1460 non-null   object
 15  HouseStyle     1460 non-null   object
 16  OverallQual    1460 non-null   int64
 17  OverallCond    1460 non-null   int64
 18  YearBuilt      1460 non-null   int64
 19  YearRemodAdd   1460 non-null   int64
 20  RoofStyle      1460 non-null   object
 21  RoofMatl       1460 non-null   object
 22  Exterior1st    1460 non-null   object
 23  Exterior2nd    1460 non-null   object
 24  MasVnrType     1460 non-null   object
 25  MasVnrArea     1460 non-null   float64
 26  ExterQual      1460 non-null   object
 27  ExterCond      1460 non-null   object
 28  Foundation     1460 non-null   object
 29  BsmtQual       1460 non-null   object
 30  BsmtCond       1460 non-null   object
 31  BsmtExposure   1460 non-null   object
 32  BsmtFinType1   1460 non-null   object
 33  BsmtFinSF1     1460 non-null   int64
 34  BsmtFinType2   1460 non-null   object
 35  BsmtFinSF2     1460 non-null   int64
 36  BsmtUnfSF      1460 non-null   int64
 37  TotalBsmtSF    1460 non-null   int64
 38  Heating        1460 non-null   object
 39  HeatingQC      1460 non-null   object
 40  CentralAir     1460 non-null   object
 41  Electrical     1460 non-null   object
 42  1stFlrSF       1460 non-null   int64
 43  2ndFlrSF       1460 non-null   int64
 44  LowQualFinSF   1460 non-null   int64
 45  GrLivArea      1460 non-null   int64
 46  BsmtFullBath   1460 non-null   int64
 47  BsmtHalfBath   1460 non-null   int64
 48  FullBath       1460 non-null   int64
 49  HalfBath       1460 non-null   int64
 50  BedroomAbvGr   1460 non-null   int64
 51  KitchenAbvGr   1460 non-null   int64
 52  KitchenQual    1460 non-null   object
 53  TotRmsAbvGrd   1460 non-null   int64
 54  Functional     1460 non-null   object
 55  Fireplaces     1460 non-null   int64
 56  FireplaceQu    1460 non-null   object
 57  GarageType     1460 non-null   object
 58  GarageYrBlt    1460 non-null   float64
 59  GarageFinish   1460 non-null   object
 60  GarageCars     1460 non-null   int64
 61  GarageArea     1460 non-null   int64
 62  GarageQual     1460 non-null   object
 63  PavedDrive     1460 non-null   object
 64  WoodDeckSF     1460 non-null   int64
 65  OpenPorchSF    1460 non-null   int64
 66  EnclosedPorch  1460 non-null   int64
 67  3SsnPorch      1460 non-null   int64
 68  ScreenPorch    1460 non-null   int64
 69  PoolArea       1460 non-null   int64
 70  MiscVal        1460 non-null   int64
 71  MoSold         1460 non-null   int64
 72  YrSold         1460 non-null   int64
 73  SaleType       1460 non-null   object
 74  SaleCondition  1460 non-null   object
 75  SalePrice      1460 non-null   int64
dtypes: float64(3), int64(35), object(38)
memory usage: 867.0+ KB

In [577]:
df_object=df.select_dtypes(include='object')
df_object

,MSZoning,Street,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,Condition1,Condition2,...,Electrical,KitchenQual,Functional,FireplaceQu,GarageType,GarageFinish,GarageQual,PavedDrive,SaleType,SaleCondition
0,RL,Pave,Reg,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,Norm,...,SBrkr,Gd,Typ,no,Attchd,RFn,TA,Y,WD,Normal
1,RL,Pave,Reg,Lvl,AllPub,FR2,Gtl,Veenker,Feedr,Norm,...,SBrkr,TA,Typ,TA,Attchd,RFn,TA,Y,WD,Normal
2,RL,Pave,IR1,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,Norm,...,SBrkr,Gd,Typ,TA,Attchd,RFn,TA,Y,WD,Normal
3,RL,Pave,IR1,Lvl,AllPub,Corner,Gtl,Crawfor,Norm,Norm,...,SBrkr,Gd,Typ,Gd,Detchd,Unf,TA,Y,WD,Abnorml
4,RL,Pave,IR1,Lvl,AllPub,FR2,Gtl,NoRidge,Norm,Norm,...,SBrkr,Gd,Typ,TA,Attchd,RFn,TA,Y,WD,Normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,RL,Pave,Reg,Lvl,AllPub,Inside,Gtl,Gilbert,Norm,Norm,...,SBrkr,TA,Typ,TA,Attchd,RFn,TA,Y,WD,Normal
1456,RL,Pave,Reg,Lvl,AllPub,Inside,Gtl,NWAmes,Norm,Norm,...,SBrkr,TA,Min1,TA,Attchd,Unf,TA,Y,WD,Normal
1457,RL,Pave,Reg,Lvl,AllPub,Inside,Gtl,Crawfor,Norm,Norm,...,SBrkr,Gd,Typ,Gd,Attchd,RFn,TA,Y,WD,Normal
1458,RL,Pave,Reg,Lvl,AllPub,Inside,Gtl,NAmes,Norm,Norm,...,FuseA,Gd,Typ,no,Attchd,Unf,TA,Y,WD,Normal
1459,RL,Pave,Reg,Lvl,AllPub,Inside,Gtl,Edwards,Norm,Norm,...,SBrkr,TA,Typ,no,Attchd,Fin,TA,Y,WD,Normal

In [578]:
df_num=df.select_dtypes(exclude='object')
df_num

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,...,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SalePrice
0,1,60,65.0,8450,7,5,2003,2003,196.0,706,...,0,61,0,0,0,0,0,2,2008,208500
1,2,20,80.0,9600,6,8,1976,1976,0.0,978,...,298,0,0,0,0,0,0,5,2007,181500
2,3,60,68.0,11250,7,5,2001,2002,162.0,486,...,0,42,0,0,0,0,0,9,2008,223500
3,4,70,60.0,9550,7,5,1915,1970,0.0,216,...,0,35,272,0,0,0,0,2,2006,140000
4,5,60,84.0,14260,8,5,2000,2000,350.0,655,...,192,84,0,0,0,0,0,12,2008,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,62.0,7917,6,5,1999,2000,0.0,0,...,0,40,0,0,0,0,0,8,2007,175000
1456,1457,20,85.0,13175,6,6,1978,1988,119.0,790,...,349,0,0,0,0,0,0,2,2010,210000
1457,1458,70,66.0,9042,7,9,1941,2006,0.0,275,...,0,60,0,0,0,0,2500,5,2010,266500
1458,1459,20,68.0,9717,5,6,1950,1996,0.0,49,...,366,0,112,0,0,0,0,4,2010,142125
1459,1460,20,75.0,9937,5,6,1965,1965,0.0,830,...,736,68,0,0,0,0,0,6,2008,147500

In [579]:
df_dummies=pd.get_dummies(df_object,drop_first=True)
df_dummies

,MSZoning_FV,MSZoning_RH,MSZoning_RL,MSZoning_RM,Street_Pave,LotShape_IR2,LotShape_IR3,LotShape_Reg,LandContour_HLS,LandContour_Low,...,SaleType_ConLI,SaleType_ConLw,SaleType_New,SaleType_Oth,SaleType_WD,SaleCondition_AdjLand,SaleCondition_Alloca,SaleCondition_Family,SaleCondition_Normal,SaleCondition_Partial
0,0,0,1,0,1,0,0,1,0,0,...,0,0,0,0,1,0,0,0,1,0
1,0,0,1,0,1,0,0,1,0,0,...,0,0,0,0,1,0,0,0,1,0
2,0,0,1,0,1,0,0,0,0,0,...,0,0,0,0,1,0,0,0,1,0
3,0,0,1,0,1,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
4,0,0,1,0,1,0,0,0,0,0,...,0,0,0,0,1,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,0,0,1,0,1,0,0,1,0,0,...,0,0,0,0,1,0,0,0,1,0
1456,0,0,1,0,1,0,0,1,0,0,...,0,0,0,0,1,0,0,0,1,0
1457,0,0,1,0,1,0,0,1,0,0,...,0,0,0,0,1,0,0,0,1,0
1458,0,0,1,0,1,0,0,1,0,0,...,0,0,0,0,1,0,0,0,1,0
1459,0,0,1,0,1,0,0,1,0,0,...,0,0,0,0,1,0,0,0,1,0

In [581]:
# scale the data and drop the target variable and concat with categorical columns and proceed for pca Fitting
from sklearn.preprocessing import StandardScaler
df_n_sc=StandardScaler().fit_transform(df_num)
df_n_sc=pd.DataFrame(df_n_sc)
df_n_sc

,0,1,2,3,4,5,6,7,8,9,...,28,29,30,31,32,33,34,35,36,37
0,-1.730865,0.073375,-0.220875,-0.207142,0.651479,-0.517200,1.050994,0.878668,0.514104,0.575425,...,-0.752176,0.216503,-0.359325,-0.116339,-0.270208,-0.068692,-0.087688,-1.599111,0.138777,0.347273
1,-1.728492,-0.872563,0.460320,-0.091886,-0.071836,2.179628,0.156734,-0.429577,-0.570750,1.171992,...,1.626195,-0.704483,-0.359325,-0.116339,-0.270208,-0.068692,-0.087688,-0.489110,-0.614439,0.007288
2,-1.726120,0.073375,-0.084636,0.073480,0.651479,-0.517200,0.984752,0.830215,0.325915,0.092907,...,-0.752176,-0.070361,-0.359325,-0.116339,-0.270208,-0.068692,-0.087688,0.990891,0.138777,0.536154
3,-1.723747,0.309859,-0.447940,-0.096897,0.651479,-0.517200,-1.863632,-0.720298,-0.570750,-0.499274,...,-0.752176,-0.176048,4.092524,-0.116339,-0.270208,-0.068692,-0.087688,-1.599111,-1.367655,-0.515281
4,-1.721374,0.073375,0.641972,0.375148,1.374795,-0.517200,0.951632,0.733308,1.366489,0.463568,...,0.780197,0.563760,-0.359325,-0.116339,-0.270208,-0.068692,-0.087688,2.100892,0.138777,0.869843
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1.721374,0.073375,-0.357114,-0.260560,-0.071836,-0.517200,0.918511,0.733308,-0.570750,-0.973018,...,-0.752176,-0.100558,-0.359325,-0.116339,-0.270208,-0.068692,-0.087688,0.620891,-0.614439,-0.074560
1456,1.723747,-0.872563,0.687385,0.266407,-0.071836,0.381743,0.222975,0.151865,0.087911,0.759659,...,2.033231,-0.704483,-0.359325,-0.116339,-0.270208,-0.068692,-0.087688,-1.599111,1.645210,0.366161
1457,1.726120,0.309859,-0.175462,-0.147810,0.651479,3.078570,-1.002492,1.024029,-0.570750,-0.369871,...,-0.752176,0.201405,-0.359325,-0.116339,-0.270208,-0.068692,4.953112,-0.489110,1.645210,1.077611
1458,1.728492,-0.872563,-0.084636,-0.080160,-0.795151,0.381743,-0.704406,0.539493,-0.570750,-0.865548,...,2.168910,-0.704483,1.473789,-0.116339,-0.270208,-0.068692,-0.087688,-0.859110,1.645210,-0.488523
1459,1.730865,-0.872563,0.233255,-0.058112,-0.795151,0.381743,-0.207594,-0.962566,-0.570750,0.847389,...,5.121921,0.322190,-0.359325,-0.116339,-0.270208,-0.068692,-0.087688,-0.119110,0.138777,-0.420841

In [584]:
# scaled target variable
df_target=df_n_sc.iloc[:,37]
df_target

0       0.347273
1       0.007288
2       0.536154
3      -0.515281
4       0.869843
          ...
1455   -0.074560
1456    0.366161
1457    1.077611
1458   -0.488523
1459   -0.420841
Name: 37, Length: 1460, dtype: float64

In [585]:
# numerical cols without target
df_no=df_n_sc.iloc[:,0:37]
df_no

,0,1,2,3,4,5,6,7,8,9,...,27,28,29,30,31,32,33,34,35,36
0,-1.730865,0.073375,-0.220875,-0.207142,0.651479,-0.517200,1.050994,0.878668,0.514104,0.575425,...,0.351000,-0.752176,0.216503,-0.359325,-0.116339,-0.270208,-0.068692,-0.087688,-1.599111,0.138777
1,-1.728492,-0.872563,0.460320,-0.091886,-0.071836,2.179628,0.156734,-0.429577,-0.570750,1.171992,...,-0.060731,1.626195,-0.704483,-0.359325,-0.116339,-0.270208,-0.068692,-0.087688,-0.489110,-0.614439
2,-1.726120,0.073375,-0.084636,0.073480,0.651479,-0.517200,0.984752,0.830215,0.325915,0.092907,...,0.631726,-0.752176,-0.070361,-0.359325,-0.116339,-0.270208,-0.068692,-0.087688,0.990891,0.138777
3,-1.723747,0.309859,-0.447940,-0.096897,0.651479,-0.517200,-1.863632,-0.720298,-0.570750,-0.499274,...,0.790804,-0.752176,-0.176048,4.092524,-0.116339,-0.270208,-0.068692,-0.087688,-1.599111,-1.367655
4,-1.721374,0.073375,0.641972,0.375148,1.374795,-0.517200,0.951632,0.733308,1.366489,0.463568,...,1.698485,0.780197,0.563760,-0.359325,-0.116339,-0.270208,-0.068692,-0.087688,2.100892,0.138777
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1.721374,0.073375,-0.357114,-0.260560,-0.071836,-0.517200,0.918511,0.733308,-0.570750,-0.973018,...,-0.060731,-0.752176,-0.100558,-0.359325,-0.116339,-0.270208,-0.068692,-0.087688,0.620891,-0.614439
1456,1.723747,-0.872563,0.687385,0.266407,-0.071836,0.381743,0.222975,0.151865,0.087911,0.759659,...,0.126420,2.033231,-0.704483,-0.359325,-0.116339,-0.270208,-0.068692,-0.087688,-1.599111,1.645210
1457,1.726120,0.309859,-0.175462,-0.147810,0.651479,3.078570,-1.002492,1.024029,-0.570750,-0.369871,...,-1.033914,-0.752176,0.201405,-0.359325,-0.116339,-0.270208,-0.068692,4.953112,-0.489110,1.645210
1458,1.728492,-0.872563,-0.084636,-0.080160,-0.795151,0.381743,-0.704406,0.539493,-0.570750,-0.865548,...,-1.090059,2.168910,-0.704483,1.473789,-0.116339,-0.270208,-0.068692,-0.087688,-0.859110,1.645210
1459,1.730865,-0.872563,0.233255,-0.058112,-0.795151,0.381743,-0.207594,-0.962566,-0.570750,0.847389,...,-0.921624,5.121921,0.322190,-0.359325,-0.116339,-0.270208,-0.068692,-0.087688,-0.119110,0.138777

In [603]:
df_joined=pd.concat([df_no,df_ob],axis=1)
df_joined

,0,1,2,3,4,5,6,7,8,9,...,SaleType_ConLI,SaleType_ConLw,SaleType_New,SaleType_Oth,SaleType_WD,SaleCondition_AdjLand,SaleCondition_Alloca,SaleCondition_Family,SaleCondition_Normal,SaleCondition_Partial
0,-1.730865,0.073375,-0.220875,-0.207142,0.651479,-0.517200,1.050994,0.878668,0.514104,0.575425,...,0,0,0,0,1,0,0,0,1,0
1,-1.728492,-0.872563,0.460320,-0.091886,-0.071836,2.179628,0.156734,-0.429577,-0.570750,1.171992,...,0,0,0,0,1,0,0,0,1,0
2,-1.726120,0.073375,-0.084636,0.073480,0.651479,-0.517200,0.984752,0.830215,0.325915,0.092907,...,0,0,0,0,1,0,0,0,1,0
3,-1.723747,0.309859,-0.447940,-0.096897,0.651479,-0.517200,-1.863632,-0.720298,-0.570750,-0.499274,...,0,0,0,0,1,0,0,0,0,0
4,-1.721374,0.073375,0.641972,0.375148,1.374795,-0.517200,0.951632,0.733308,1.366489,0.463568,...,0,0,0,0,1,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1.721374,0.073375,-0.357114,-0.260560,-0.071836,-0.517200,0.918511,0.733308,-0.570750,-0.973018,...,0,0,0,0,1,0,0,0,1,0
1456,1.723747,-0.872563,0.687385,0.266407,-0.071836,0.381743,0.222975,0.151865,0.087911,0.759659,...,0,0,0,0,1,0,0,0,1,0
1457,1.726120,0.309859,-0.175462,-0.147810,0.651479,3.078570,-1.002492,1.024029,-0.570750,-0.369871,...,0,0,0,0,1,0,0,0,1,0
1458,1.728492,-0.872563,-0.084636,-0.080160,-0.795151,0.381743,-0.704406,0.539493,-0.570750,-0.865548,...,0,0,0,0,1,0,0,0,1,0
1459,1.730865,-0.872563,0.233255,-0.058112,-0.795151,0.381743,-0.207594,-0.962566,-0.570750,0.847389,...,0,0,0,0,1,0,0,0,1,0

In [604]:
 #PCA FITTING
from sklearn.decomposition import PCA

In [605]:
pca=PCA(random_state=100)

In [606]:
pca_data =pca.fit(df_joined)
pca_data

PCA(random_state=100)

In [607]:
print(pca_data.explained_variance_ratio_)
print('\ncum_ratio\n',np.cumsum(pca_data.explained_variance_ratio_))

[1.73211125e-01 7.49662740e-02 6.63718000e-02 4.64608538e-02
 3.32491876e-02 2.81404170e-02 2.64698291e-02 2.52990786e-02
 2.52195696e-02 2.42534824e-02 2.34105606e-02 2.28715201e-02
 2.23215203e-02 2.17614025e-02 2.08583572e-02 2.02259246e-02
 1.90834017e-02 1.86274386e-02 1.79669162e-02 1.77662518e-02
 1.69926858e-02 1.54839841e-02 1.43018591e-02 1.33751065e-02
 1.22327114e-02 1.11668445e-02 1.00832202e-02 8.97930436e-03
 7.99752201e-03 6.73920418e-03 6.49174458e-03 6.32586234e-03
 5.78538119e-03 5.71925145e-03 5.70210499e-03 5.18513457e-03
 5.05335177e-03 4.81446089e-03 4.59255731e-03 4.38629385e-03
 4.31943268e-03 3.92724122e-03 3.86914598e-03 3.51394936e-03
 3.50666057e-03 3.41732502e-03 3.19096235e-03 3.08358893e-03
 2.88309822e-03 2.81680215e-03 2.67598882e-03 2.61655039e-03
 2.31281584e-03 2.15204298e-03 2.03182837e-03 2.02225786e-03
 2.00296114e-03 1.85818285e-03 1.72261162e-03 1.71090929e-03
 1.59699481e-03 1.47214945e-03 1.41046496e-03 1.36583392e-03
 1.24872272e-03 1.22937109e-03 1.20152435e-03 1.19785275e-03
 1.12268878e-03 1.01985249e-03 1.00434669e-03 9.94401467e-04
 9.63387107e-04 9.48430019e-04 8.99223819e-04 8.48445370e-04
 8.06830316e-04 7.81130478e-04 7.70732326e-04 7.61604111e-04
 7.57535449e-04 7.18848357e-04 6.98326340e-04 6.79110240e-04
 6.46749881e-04 6.27471451e-04 6.19739741e-04 6.03190521e-04
 5.78826922e-04 5.69249678e-04 5.40647087e-04 5.33447770e-04
 5.22874431e-04 4.96343722e-04 4.92429081e-04 4.74502356e-04
 4.67587386e-04 4.58274611e-04 4.32292996e-04 4.01873952e-04
 3.91656165e-04 3.79749138e-04 3.56177678e-04 3.44666699e-04
 3.36166966e-04 3.26088522e-04 3.12301725e-04 2.98383431e-04
 2.92749620e-04 2.86678605e-04 2.78119613e-04 2.71689967e-04
 2.61413507e-04 2.50012229e-04 2.45347318e-04 2.35746700e-04
 2.25678011e-04 2.23285577e-04 2.21939101e-04 2.13181729e-04
 2.08824929e-04 2.03160965e-04 1.99495775e-04 1.84680915e-04
 1.75342681e-04 1.68706497e-04 1.65256718e-04 1.61788600e-04
 1.59718301e-04 1.58424071e-04 1.49452136e-04 1.45527436e-04
 1.41387730e-04 1.33812113e-04 1.25554629e-04 1.21854189e-04
 1.17073394e-04 1.14633908e-04 1.13209457e-04 1.08795640e-04
 1.07605651e-04 1.07056227e-04 1.01240122e-04 9.86631231e-05
 9.54784500e-05 9.22726803e-05 8.72991624e-05 8.41428336e-05
 8.08549562e-05 7.87989185e-05 7.62652729e-05 7.00721356e-05
 6.63654366e-05 6.53369553e-05 6.26984122e-05 6.17494977e-05
 5.96541432e-05 5.76362138e-05 5.72342468e-05 5.45734229e-05
 5.41128549e-05 5.22196347e-05 4.79955091e-05 4.58033120e-05
 4.40964574e-05 4.27327799e-05 4.09920161e-05 3.98213742e-05
 3.86368729e-05 3.71730362e-05 3.58583120e-05 3.48384420e-05
 3.21295858e-05 2.97176916e-05 2.86875117e-05 2.72529325e-05
 2.63232140e-05 2.53411979e-05 2.43951985e-05 2.39470045e-05
 2.33485557e-05 2.27111903e-05 2.23158390e-05 2.14708701e-05
 2.02809466e-05 1.85150034e-05 1.84872397e-05 1.70963856e-05
 1.52181091e-05 1.50581010e-05 1.42005907e-05 1.29960322e-05
 1.28009491e-05 1.22165456e-05 1.14732997e-05 1.10624380e-05
 1.07224403e-05 1.06347592e-05 1.00896684e-05 9.25274766e-06
 7.29562541e-06 7.23443632e-06 6.01675854e-06 5.31364015e-06
 4.27835959e-06 3.31097826e-06 2.90968437e-06 2.47929171e-06
 2.21063713e-06 2.12660967e-06 9.07097013e-07 3.41598712e-32
 8.76296650e-34 8.76296650e-34]

cum_ratio
 [0.17321112 0.2481774  0.3145492  0.36101005 0.39425924 0.42239966
 0.44886949 0.47416856 0.49938813 0.52364162 0.54705218 0.5699237
 0.59224522 0.61400662 0.63486498 0.6550909  0.6741743  0.69280174
 0.71076866 0.72853491 0.7455276  0.76101158 0.77531344 0.78868855
 0.80092126 0.8120881  0.82217132 0.83115063 0.83914815 0.84588735
 0.8523791  0.85870496 0.86449034 0.87020959 0.8759117  0.88109683
 0.88615018 0.89096464 0.8955572  0.8999435  0.90426293 0.90819017
 0.91205932 0.91557326 0.91907993 0.92249725 0.92568821 0.9287718
 0.9316549  0.9344717  0.93714769 0.93976424 0.94207706 0.9442291
 0.94626093 0.94828319 0.95028615 0.95214433 0.95386694 0.95557785
 0.95717485 0.958647   0.96005746 0.96142329 0.96267202 0.96390139
 0.96510291 0.96630077 0.96742345 0.96844331 0.96944765 0.97044205
 0.97140544 0.97235387 0.9732531  0.97410154 0.97490837 0.9756895
 0.97646023 0.97722184 0.97797937 0.97869822 0.97939655 0.98007566
 0.98072241 0.98134988 0.98196962 0.98257281 0.98315164 0.98372089
 0.98426153 0.98479498 0.98531786 0.9858142  0.98630663 0.98678113
 0.98724872 0.98770699 0.98813929 0.98854116 0.98893282 0.98931257
 0.98966874 0.99001341 0.99034958 0.99067567 0.99098797 0.99128635
 0.9915791  0.99186578 0.9921439  0.99241559 0.992677   0.99292701
 0.99317236 0.99340811 0.99363379 0.99385707 0.99407901 0.99429219
 0.99450102 0.99470418 0.99490367 0.99508835 0.9952637  0.9954324
 0.99559766 0.99575945 0.99591917 0.99607759 0.99622704 0.99637257
 0.99651396 0.99664777 0.99677333 0.99689518 0.99701225 0.99712689
 0.9972401  0.99734889 0.9974565  0.99756355 0.99766479 0.99776346
 0.99785894 0.99795121 0.99803851 0.99812265 0.99820351 0.9982823
 0.99835857 0.99842864 0.99849501 0.99856034 0.99862304 0.99868479
 0.99874445 0.99880208 0.99885932 0.99891389 0.998968   0.99902022
 0.99906822 0.99911402 0.99915812 0.99920085 0.99924184 0.99928166
 0.9993203  0.99935747 0.99939333 0.99942817 0.9994603  0.99949002
 0.99951871 0.99954596 0.99957228 0.99959762 0.99962202 0.99964597
 0.99966931 0.99969202 0.99971434 0.99973581 0.99975609 0.99977461
 0.99979309 0.99981019 0.99982541 0.99984047 0.99985467 0.99986766
 0.99988046 0.99989268 0.99990415 0.99991522 0.99992594 0.99993657
 0.99994666 0.99995592 0.99996321 0.99997045 0.99997646 0.99998178
 0.99998606 0.99998937 0.99999228 0.99999476 0.99999697 0.99999909
 1.         1.         1.         1.        ]

In [608]:
cum_ratio=np.cumsum(pca_data.explained_variance_ratio_)
cum_ratio[cum_ratio<.96]

array([0.17321112, 0.2481774 , 0.3145492 , 0.36101005, 0.39425924,
       0.42239966, 0.44886949, 0.47416856, 0.49938813, 0.52364162,
       0.54705218, 0.5699237 , 0.59224522, 0.61400662, 0.63486498,
       0.6550909 , 0.6741743 , 0.69280174, 0.71076866, 0.72853491,
       0.7455276 , 0.76101158, 0.77531344, 0.78868855, 0.80092126,
       0.8120881 , 0.82217132, 0.83115063, 0.83914815, 0.84588735,
       0.8523791 , 0.85870496, 0.86449034, 0.87020959, 0.8759117 ,
       0.88109683, 0.88615018, 0.89096464, 0.8955572 , 0.8999435 ,
       0.90426293, 0.90819017, 0.91205932, 0.91557326, 0.91907993,
       0.92249725, 0.92568821, 0.9287718 , 0.9316549 , 0.9344717 ,
       0.93714769, 0.93976424, 0.94207706, 0.9442291 , 0.94626093,
       0.94828319, 0.95028615, 0.95214433, 0.95386694, 0.95557785,
       0.95717485, 0.958647  ])

In [609]:
len(cum_ratio[cum_ratio<.96])

62

In [610]:
pca_data_t=pca.transform(df_joined)
pca_data_t

array([[ 2.13170227e+00,  4.48592692e-01, -2.15443087e+00, ...,
         4.80898949e-16, -4.34482123e-17,  3.88301109e-16],
       [-3.33217957e-01, -1.00922052e+00,  1.52735644e+00, ...,
         3.02607831e-16, -3.12492981e-16,  6.29969773e-16],
       [ 2.42239993e+00,  3.48704867e-01, -1.82708156e+00, ...,
         1.20217921e-16,  7.24546397e-16, -1.04859203e-15],
       ...,
       [ 2.71337555e-01,  3.56055613e+00,  1.23788549e+00, ...,
         2.20542838e-15,  1.48041827e-15, -1.37331058e-15],
       [-3.04888998e+00, -1.99024437e+00,  1.75983677e+00, ...,
        -1.51738560e-15,  1.31505711e-15, -1.23567111e-15],
       [-1.17884051e+00, -1.34409961e+00,  1.65958773e+00, ...,
        -4.40597511e-16,  9.58571436e-16, -4.17694786e-16]])

In [613]:
df_pca=pd.DataFrame(pca_data_t)
df_pca

,0,1,2,3,4,5,6,7,8,9,...,204,205,206,207,208,209,210,211,212,213
0,2.131702,0.448593,-2.154431,-1.807948,0.457863,0.277474,-1.260242,-0.800114,-0.767670,-0.508811,...,0.002747,-0.000908,-0.001329,0.001780,-0.000878,-0.000801,0.001254,4.808989e-16,-4.344821e-17,3.883011e-16
1,-0.333218,-1.009221,1.527356,-0.372204,-1.791769,-0.816898,-0.437148,3.476146,-0.029845,-0.543805,...,-0.011765,-0.002560,0.003350,-0.004559,0.000050,0.002100,-0.002332,3.026078e-16,-3.124930e-16,6.299698e-16
2,2.422400,0.348705,-1.827082,-1.502779,-0.301435,-0.306566,-0.203261,-0.409543,0.212704,-0.528617,...,0.000295,0.000924,-0.000712,-0.000341,-0.000141,-0.002592,0.000777,1.202179e-16,7.245464e-16,-1.048592e-15
3,-0.494520,1.350358,0.529983,-0.064920,0.041202,1.586327,1.139240,-1.545797,-1.271816,-2.035209,...,0.009609,-0.002098,-0.004080,0.005104,0.005736,-0.001062,0.006342,-3.225516e-16,1.475543e-16,8.211688e-16
4,4.918049,1.412565,-0.435021,-1.424890,-0.182019,-0.701694,-0.235089,0.142456,0.469642,-1.076996,...,0.001651,-0.000136,0.000612,0.000192,-0.000350,0.000738,0.004430,6.093752e-16,3.560803e-16,-6.231511e-16
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1.074782,1.428343,-2.157352,0.405535,-0.450636,-0.364622,-0.130258,-0.804462,1.443565,0.190340,...,-0.003926,-0.002273,0.001661,0.000147,-0.000731,-0.001597,-0.000787,5.552413e-16,9.460489e-16,-1.902130e-15
1456,1.928161,-1.515829,2.971475,-0.281864,0.459083,0.511429,-1.665021,0.139814,-1.101206,1.485530,...,0.002579,0.003839,0.000353,0.001628,0.000207,-0.002494,-0.004237,5.332349e-17,-4.220138e-17,2.772246e-16
1457,0.271338,3.560556,1.237885,0.179136,-1.801699,2.076822,-0.391503,2.029955,-2.302323,1.557846,...,-0.000015,-0.009737,-0.023606,0.002179,0.009037,-0.003967,-0.003589,2.205428e-15,1.480418e-15,-1.373311e-15
1458,-3.048890,-1.990244,1.759837,-1.095131,-0.867441,2.383021,-1.954632,0.297306,0.285706,2.846148,...,0.001869,-0.008192,0.002462,0.001004,-0.003018,0.003714,0.003905,-1.517386e-15,1.315057e-15,-1.235671e-15
1459,-1.178841,-1.344100,1.659588,-1.889909,-0.357308,0.834724,-1.804559,0.577341,1.487705,0.649228,...,0.006143,-0.004089,-0.002604,-0.001083,0.003330,0.002829,-0.005478,-4.405975e-16,9.585714e-16,-4.176948e-16

In [614]:
# PCA Components extraction
df_pca_subset=pd.DataFrame(pca_data_t[:,0:62],columns=['PC'+str(i) for i in range(62)])
df_pca_subset

,PC0,PC1,PC2,PC3,PC4,PC5,PC6,PC7,PC8,PC9,...,PC52,PC53,PC54,PC55,PC56,PC57,PC58,PC59,PC60,PC61
0,2.131702,0.448593,-2.154431,-1.807948,0.457863,0.277474,-1.260242,-0.800114,-0.767670,-0.508811,...,0.006055,-0.240509,0.030801,-0.186085,0.344441,-0.143292,-0.031315,0.202033,0.217901,0.199033
1,-0.333218,-1.009221,1.527356,-0.372204,-1.791769,-0.816898,-0.437148,3.476146,-0.029845,-0.543805,...,0.642401,-0.037382,0.273763,-0.139384,-0.167517,-0.193536,-0.223854,-0.139140,0.140165,-0.051313
2,2.422400,0.348705,-1.827082,-1.502779,-0.301435,-0.306566,-0.203261,-0.409543,0.212704,-0.528617,...,-0.250082,-0.488986,0.431729,0.018066,0.280718,0.020983,-0.134669,0.227009,0.091255,0.215239
3,-0.494520,1.350358,0.529983,-0.064920,0.041202,1.586327,1.139240,-1.545797,-1.271816,-2.035209,...,-0.234896,0.844786,-0.087202,-0.118766,-0.861634,-0.108184,-0.194950,0.375525,-0.101608,1.337041
4,4.918049,1.412565,-0.435021,-1.424890,-0.182019,-0.701694,-0.235089,0.142456,0.469642,-1.076996,...,0.028983,0.045702,0.005407,0.104688,0.073380,-0.171555,-0.026264,-0.206603,-0.185772,-0.042547
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1.074782,1.428343,-2.157352,0.405535,-0.450636,-0.364622,-0.130258,-0.804462,1.443565,0.190340,...,0.126000,0.150353,0.119092,0.087993,-0.041058,0.106104,0.075893,-0.197473,0.089028,-0.179078
1456,1.928161,-1.515829,2.971475,-0.281864,0.459083,0.511429,-1.665021,0.139814,-1.101206,1.485530,...,0.051425,0.136173,0.066911,0.521136,-0.259775,0.965716,-0.453019,0.150406,-0.031371,-0.031685
1457,0.271338,3.560556,1.237885,0.179136,-1.801699,2.076822,-0.391503,2.029955,-2.302323,1.557846,...,0.253979,0.084757,0.642376,0.407136,-0.330198,-0.614464,0.249456,0.389204,-0.192207,0.681546
1458,-3.048890,-1.990244,1.759837,-1.095131,-0.867441,2.383021,-1.954632,0.297306,0.285706,2.846148,...,-0.251516,0.282315,0.294538,0.221036,-0.155506,-0.090347,0.308315,0.210705,-0.319157,-0.336381
1459,-1.178841,-1.344100,1.659588,-1.889909,-0.357308,0.834724,-1.804559,0.577341,1.487705,0.649228,...,0.325178,-0.015921,-0.382082,-0.125213,-0.134638,-0.105719,0.168713,0.086574,-0.358815,-0.052366

In [622]:
# updating the accuracy score

# create an empty dataframe to store the scores for various classification algorithms
score_card = pd.DataFrame(columns=['Model', 'Root Mean Square Error', 'R2-score'])

# append the result table for all performance scores
# performance measures considered for comparision are 'AUC', 'Precision', 'Recall','Accuracy','Kappa Score', and 'f1-score'
# compile the required information in a user defined function 

def updateScoreCard(model_name):
    global score_card
    # append the results to the dataframe 'score_card'
    # 'ignore_index = True' do not consider the index labels
    
    score_card = score_card.append({'Model': model_name,
                                        
                                        'Root Mean Square Error': np.sqrt(mean_squared_error(y_test, test_pred)) ,
                                        'R2-score': r2_score(y_test, test_pred)}, 
                                        ignore_index = True)
    return(score_card)

# LINEAR Model

In [615]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split as split
from sklearn.metrics import mean_squared_error,r2_score

In [619]:
# Dataset
x=df_pca_subset
df_target=pd.DataFrame(df_target)
y=df_target
print(y.shape)
x.shape

(1460, 1)

(1460, 62)

In [625]:
# splitting
x_train,x_test,y_train,y_test=split(x,y,test_size=0.3,random_state=42)

In [626]:


# model fitting
lr=LinearRegression()
lr.fit(x_train,y_train)

#Model predict
train_pred=lr.predict(x_train)
test_pred=lr.predict(x_test)


# Results
print('Train RMSE:',np.sqrt(mean_squared_error(y_train,train_pred)))
print('Train R2score:',r2_score(y_train,train_pred))

print('Test RMSE:',np.sqrt(mean_squared_error(y_test,test_pred)))
print('Test R2score:',r2_score(y_test,test_pred))

Train RMSE: 0.4048899033527544
Train R2score: 0.828213727470014
Test RMSE: 0.4150262708440532
Test R2score: 0.8443236471237189

In [624]:
updateScoreCard(lr)

                Model  Root Mean Square Error  R2-score
0  LinearRegression()                0.415026  0.844324

LinearRegression()